import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import * as S from '../styles/diferenciais';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';


const Sobre = () => {

    return (
        <>
            <Head>
                <title>Setima</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/Ativo 162.png"/>
            </Head>
            <NavBar/>
            <S.Main>
                <S.ContainerPrincipal>
                    <S.SpanPrincipal>DIFERENCIAIS</S.SpanPrincipal>
                    <S.SegundoSobre>
                        <S.ContainerIconeSobre>
                            <S.IconeSobre src='/Roteiro.svg'/>
                            <S.MiniContainerSegundoSobre>
                                <S.SpanSobre3>ROTEIRO</S.SpanSobre3>
                                <S.SpanSobre2>Lorem ipsum dolor sit amet, consectetur adipiscing
                                                                        elit. Aliquam ac sem neque usce fermentum odio.</S.SpanSobre2>
                            </S.MiniContainerSegundoSobre>
                        </S.ContainerIconeSobre>
                        <S.ContainerIconeSobre>
                            <S.IconeSobre src='/ColorBranding.svg'/>
                            <S.MiniContainerSegundoSobre>
                                <S.SpanSobre3>COLOR BRANDING</S.SpanSobre3>
                                <S.SpanSobre2>Lorem ipsum dolor sit amet, consectetur adipiscing
                                                                        elit. Aliquam ac sem neque usce fermentum odio.</S.SpanSobre2>
                            </S.MiniContainerSegundoSobre>
                        </S.ContainerIconeSobre>
                        <S.ContainerIconeSobre>
                            <S.IconeSobre src='/MoodBoard.svg'/>
                            <S.MiniContainerSegundoSobre>
                                <S.SpanSobre3>MOODBOARD</S.SpanSobre3>
                                <S.SpanSobre2>Lorem ipsum dolor sit amet, consectetur adipiscing
                                                                        elit. Aliquam ac sem neque usce fermentum odio.</S.SpanSobre2>
                            </S.MiniContainerSegundoSobre>
                        </S.ContainerIconeSobre>
                        <S.ContainerIconeSobre>
                            <S.IconeSobre src='/VFX.svg'/>
                            <S.MiniContainerSegundoSobre>
                                <S.SpanSobre3>VFX</S.SpanSobre3>
                                <S.SpanSobre2>Lorem ipsum dolor sit amet, consectetur adipiscing
                                                                        elit. Aliquam ac sem neque usce fermentum odio.</S.SpanSobre2>
                            </S.MiniContainerSegundoSobre>
                        </S.ContainerIconeSobre>
                    </S.SegundoSobre>
                </S.ContainerPrincipal>
            </S.Main>
            <Footer/>
        </>
    );
}

export default Sobre;
